const fs = require('fs');
const assert = require('assert/strict');
const Module = require('module');
const path = require('path');
const ts = require('typescript');
const originalResolve = Module._resolveFilename;
Module._resolveFilename = function(id, ...args) { return originalResolve.call(this, id.startsWith('@/') ? path.resolve(id.slice(2)) : id, ...args); };
for (const ext of ['.ts', '.tsx']) require.extensions[ext] = (mod, name) => mod._compile(ts.transpileModule(fs.readFileSync(name, 'utf8'), {compilerOptions:{module:ts.ModuleKind.CommonJS, jsx:ts.JsxEmit.React, esModuleInterop:true}}).outputText, name);
const React = require('react');
const { renderToStaticMarkup } = require('react-dom/server');
const { ProposalDocument } = require('../components/proposal/ProposalDocument.tsx');
const { buildDocModelFromProposal } = require('../lib/documentModel.ts');
const { buildDocxFile } = require('../lib/exportDocx.ts');
const JSZip = require('jszip');
(async () => {
 const model = buildDocModelFromProposal({hotel_name:'Test Hotel',services:[{code:'RM',scope_items:[{id:'b',text:'Second scope first',enabled:true,sectionHeading:'Scope'},{id:'a',text:'First scope second',enabled:true,sectionHeading:'Scope'}],fee_rows:[]}],terms:{clauses:[{id:'two',heading:'Clause Two',text:'Second clause first',enabled:true},{id:'one',heading:'Clause One',text:'First clause second',enabled:true}],pageBreaks:{'block:clause:one':true,'block:scope:["RM","a"]':true}}});
 const html = renderToStaticMarkup(React.createElement(ProposalDocument,{model}));
 assert(html.includes('data-doc-block="block:clause:one"'));
 assert.equal((html.match(/data-manual-page-break="true"/g)||[]).length,2);
 assert(html.indexOf('Second scope first') < html.indexOf('First scope second'));
 assert(html.indexOf('Second clause first') < html.indexOf('First clause second'));
 const blob = await buildDocxFile(model);
 const zip = await JSZip.loadAsync(await blob.arrayBuffer());
 const xml = await zip.file('word/document.xml').async('string');
 assert.equal((xml.match(/<w:pageBreakBefore\/>/g)||[]).length,2);
 assert(xml.indexOf('Second scope first') < xml.indexOf('First scope second'));
 assert(xml.indexOf('Second clause first') < xml.indexOf('First clause second'));
 assert(xml.includes('w:w="11906"') && xml.includes('w:h="16838"'));
 const noBreaks = renderToStaticMarkup(React.createElement(ProposalDocument,{model:{...model,pageBreaks:{}}}));
 assert(!noBreaks.includes('data-manual-page-break'));
 const source = fs.readFileSync('components/proposal/PaginatedPreview.tsx','utf8');
 const template = source.split('iframe.srcdoc = `')[1].split('`\n')[0];
 const iframe = new Function('headStyles', 'return `'+template+'`')('');
 for (const match of iframe.matchAll(/<script>([\s\S]*?)<\/script>/g)) new Function(match[1]);
 assert(!source.includes('pagedjs-edit-end'));
 console.log('PASS: saved break flags, reordered HTML/Word content, removable breaks, A4 Word size, iframe syntax, no blur refresh');
})().catch(error => {console.error(error); process.exitCode=1;});
